version: "3.7"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    labels:
      - "db.type=mysql"
      - "version=5.7"
    restart: always
    ports:
      - "3306:3306"
    privileged: true
    volumes:
      - "mysql_data:/var/lib/mysql"
    networks:
      - backend

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"
    networks:
      - backend


  etcd:
    image: quay.io/coreos/etcd:v3.4.7
    container_name: etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    restart: always
    env_file:
      - .env
    environment:
      - ETCD_HOST=${ETCD_HOST}
    volumes:
      - "etcd_data:/etcd-data"
    command:
      - /usr/local/bin/etcd
      - --data-dir=/etcd-data
      - --name
      - node1
      - --initial-advertise-peer-urls
      - http://${ETCD_HOST}:2380
      - --listen-peer-urls
      - http://0.0.0.0:2380
      - --advertise-client-urls
      - http://${ETCD_HOST}:2379
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --initial-cluster
      - node1=http://${ETCD_HOST}:2380
    networks:
      - backend

  fastdfs:
    image: sjqzhang/go-fastdfs:latest
    container_name: fastdfs
    privileged: true
    restart: always
    ports:
      - "8080:8080"
    environment:
      GO_FASTDFS_DIR: /usr/local/go-fastdfs/data
    volumes:
      - "fastdfs_data:/usr/local/go-fastdfs/data"
    networks:
      - backend

volumes:
  redis_data:
  mysql_data:
  fastdfs_data:
  etcd_data:

networks:
  backend:
    ipam:
      config:
        - subnet: 192.168.10.0/24
