# mallweb Global Configuration


# system configuration
system:
    version: '1.0.0'
    api_addr: '0.0.0.0:8888'
    project_name: 'MallWeb'

# mysql connect configuration
mysql:
    username: root
    password: 'root'
    addr: '192.168.3.233:3306'
    dbname: 'mallweb'
    max_idle_conns: 10
    max_open_conns: 10
    max_conn_lifetime: 100

# redis configuration
redis:
    addr: '192.168.3.233:6379'
    password: ''
    db: 0
    max_active: 20
    max_idle: 20
    idle_timeout: 100

# etcd configuration
etcd:
    addr: '192.168.3.233:2379'
    # 指定一次注册在注册中心的有效期
    register_ttl: 20
    # 定时向注册中心重新注册
    register_interval: 15

# jaeger configuration
jaeger:
    addr: 'localhost:6831'

# elastic configuration
elastic:
    addr: 'http://localhost:9200'
    user_name: 'elastic'
    password: 'changeme'

# logger configuration
log:
    # 日志文件名
    file_name: '/tmp/log/mallweb/mallweb.log'
    # 日志级别：  debug／info／error／fatal
    level: 'debug'
    # 打印日志的格式： json/human
    format: 'human'
    # 每个日志文件保存的最大尺寸 单位：M
    max_size: 1
    # 文件最多保存多少天
    max_backups: 5
    # 日志文件最多保存多少个备份
    max_age: 7
    # 是否压缩
    compress: true

# jwt configuration
jwt:
    secrect: 'dafkljasdlf'
    # token 过期时间，单位：小时
    expires_ime: 5


# 阿里云短信接口相关配置
sms_config:
    region_id: 'cn-hangzhou'
    access_key_id: 'LTAI4G5mBr4kSAgAPZNKpffz'
    access_key_secrect: 'DMgK7zVE7I4r58ZOjD90bocL5c7Hor'
    sign_name: '品优购商城'
    template_code: 'SMS_171115191'

