// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.4
// source: goods.proto

package goods

import (
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 全部商品分类、轮播图、促销商品展示
type FreshGoodsIndexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FreshGoodsIndexRequest) Reset() {
	*x = FreshGoodsIndexRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FreshGoodsIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreshGoodsIndexRequest) ProtoMessage() {}

func (x *FreshGoodsIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreshGoodsIndexRequest.ProtoReflect.Descriptor instead.
func (*FreshGoodsIndexRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{0}
}

type FreshGoodsIndexResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsTypes            []*GoodsType                      `protobuf:"bytes,1,rep,name=goods_types,json=goodsTypes,proto3" json:"goods_types,omitempty"`
	IndexGoodsBanners     []*IndexGoodsBanner               `protobuf:"bytes,2,rep,name=index_goods_banners,json=indexGoodsBanners,proto3" json:"index_goods_banners,omitempty"`
	IndexPromotionBanners []*IndexPromotionBanner           `protobuf:"bytes,3,rep,name=index_promotion_banners,json=indexPromotionBanners,proto3" json:"index_promotion_banners,omitempty"`
	GoodsMaps             map[string]*IndexTypeGoodsBanners `protobuf:"bytes,4,rep,name=goods_maps,json=goodsMaps,proto3" json:"goods_maps,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *FreshGoodsIndexResponse) Reset() {
	*x = FreshGoodsIndexResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FreshGoodsIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreshGoodsIndexResponse) ProtoMessage() {}

func (x *FreshGoodsIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreshGoodsIndexResponse.ProtoReflect.Descriptor instead.
func (*FreshGoodsIndexResponse) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{1}
}

func (x *FreshGoodsIndexResponse) GetGoodsTypes() []*GoodsType {
	if x != nil {
		return x.GoodsTypes
	}
	return nil
}

func (x *FreshGoodsIndexResponse) GetIndexGoodsBanners() []*IndexGoodsBanner {
	if x != nil {
		return x.IndexGoodsBanners
	}
	return nil
}

func (x *FreshGoodsIndexResponse) GetIndexPromotionBanners() []*IndexPromotionBanner {
	if x != nil {
		return x.IndexPromotionBanners
	}
	return nil
}

func (x *FreshGoodsIndexResponse) GetGoodsMaps() map[string]*IndexTypeGoodsBanners {
	if x != nil {
		return x.GoodsMaps
	}
	return nil
}

// 搜索商品
type SearchGoodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsName string `protobuf:"bytes,1,opt,name=goods_name,json=goodsName,proto3" json:"goods_name,omitempty"`
	// 排序方式
	Sort string `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
}

func (x *SearchGoodsRequest) Reset() {
	*x = SearchGoodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchGoodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGoodsRequest) ProtoMessage() {}

func (x *SearchGoodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGoodsRequest.ProtoReflect.Descriptor instead.
func (*SearchGoodsRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{2}
}

func (x *SearchGoodsRequest) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *SearchGoodsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

// 搜索商品
type SearchGoodsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsSkus []*GoodsSku `protobuf:"bytes,1,rep,name=goods_skus,json=goodsSkus,proto3" json:"goods_skus,omitempty"`
}

func (x *SearchGoodsResponse) Reset() {
	*x = SearchGoodsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchGoodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGoodsResponse) ProtoMessage() {}

func (x *SearchGoodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGoodsResponse.ProtoReflect.Descriptor instead.
func (*SearchGoodsResponse) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{3}
}

func (x *SearchGoodsResponse) GetGoodsSkus() []*GoodsSku {
	if x != nil {
		return x.GoodsSkus
	}
	return nil
}

// 商品详情
type GoodsDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsSkuId int32 `protobuf:"varint,1,opt,name=goods_sku_id,json=goodsSkuId,proto3" json:"goods_sku_id,omitempty"`
}

func (x *GoodsDetailRequest) Reset() {
	*x = GoodsDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsDetailRequest) ProtoMessage() {}

func (x *GoodsDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsDetailRequest.ProtoReflect.Descriptor instead.
func (*GoodsDetailRequest) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{4}
}

func (x *GoodsDetailRequest) GetGoodsSkuId() int32 {
	if x != nil {
		return x.GoodsSkuId
	}
	return 0
}

type GoodsDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 商品详情
	GoodsSku *GoodsSku `protobuf:"bytes,1,opt,name=goods_sku,json=goodsSku,proto3" json:"goods_sku,omitempty"`
	// 新品推荐
	GoodsSkus []*GoodsSku `protobuf:"bytes,2,rep,name=goods_skus,json=goodsSkus,proto3" json:"goods_skus,omitempty"`
}

func (x *GoodsDetailResponse) Reset() {
	*x = GoodsDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsDetailResponse) ProtoMessage() {}

func (x *GoodsDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsDetailResponse.ProtoReflect.Descriptor instead.
func (*GoodsDetailResponse) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{5}
}

func (x *GoodsDetailResponse) GetGoodsSku() *GoodsSku {
	if x != nil {
		return x.GoodsSku
	}
	return nil
}

func (x *GoodsDetailResponse) GetGoodsSkus() []*GoodsSku {
	if x != nil {
		return x.GoodsSkus
	}
	return nil
}

// 商品分类
type GoodsType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Logo  string `protobuf:"bytes,3,opt,name=Logo,proto3" json:"Logo,omitempty"`
	Image string `protobuf:"bytes,4,opt,name=Image,proto3" json:"Image,omitempty"`
}

func (x *GoodsType) Reset() {
	*x = GoodsType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsType) ProtoMessage() {}

func (x *GoodsType) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsType.ProtoReflect.Descriptor instead.
func (*GoodsType) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{6}
}

func (x *GoodsType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GoodsType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodsType) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *GoodsType) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

// 轮播图
type IndexGoodsBanner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	GoodsSkuId int32  `protobuf:"varint,2,opt,name=GoodsSkuId,proto3" json:"GoodsSkuId,omitempty"`
	Image      string `protobuf:"bytes,3,opt,name=Image,proto3" json:"Image,omitempty"`
	Index      int32  `protobuf:"varint,4,opt,name=Index,proto3" json:"Index,omitempty"`
}

func (x *IndexGoodsBanner) Reset() {
	*x = IndexGoodsBanner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexGoodsBanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexGoodsBanner) ProtoMessage() {}

func (x *IndexGoodsBanner) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexGoodsBanner.ProtoReflect.Descriptor instead.
func (*IndexGoodsBanner) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{7}
}

func (x *IndexGoodsBanner) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IndexGoodsBanner) GetGoodsSkuId() int32 {
	if x != nil {
		return x.GoodsSkuId
	}
	return 0
}

func (x *IndexGoodsBanner) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *IndexGoodsBanner) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// 促销商品展示
type IndexPromotionBanner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Url   string `protobuf:"bytes,3,opt,name=Url,proto3" json:"Url,omitempty"`
	Image string `protobuf:"bytes,4,opt,name=Image,proto3" json:"Image,omitempty"`
	Index int32  `protobuf:"varint,5,opt,name=Index,proto3" json:"Index,omitempty"`
}

func (x *IndexPromotionBanner) Reset() {
	*x = IndexPromotionBanner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexPromotionBanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexPromotionBanner) ProtoMessage() {}

func (x *IndexPromotionBanner) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexPromotionBanner.ProtoReflect.Descriptor instead.
func (*IndexPromotionBanner) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{8}
}

func (x *IndexPromotionBanner) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IndexPromotionBanner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IndexPromotionBanner) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *IndexPromotionBanner) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *IndexPromotionBanner) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// 首页分类商品展示表
type IndexTypeGoodsBanner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	GoodsTypeId int32 `protobuf:"varint,2,opt,name=GoodsTypeId,proto3" json:"GoodsTypeId,omitempty"`
	GoodsSkuId  int32 `protobuf:"varint,3,opt,name=GoodsSkuId,proto3" json:"GoodsSkuId,omitempty"`
	DisplayType int32 `protobuf:"varint,4,opt,name=DisplayType,proto3" json:"DisplayType,omitempty"`
	Index       int32 `protobuf:"varint,5,opt,name=Index,proto3" json:"Index,omitempty"`
}

func (x *IndexTypeGoodsBanner) Reset() {
	*x = IndexTypeGoodsBanner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexTypeGoodsBanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexTypeGoodsBanner) ProtoMessage() {}

func (x *IndexTypeGoodsBanner) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexTypeGoodsBanner.ProtoReflect.Descriptor instead.
func (*IndexTypeGoodsBanner) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{9}
}

func (x *IndexTypeGoodsBanner) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IndexTypeGoodsBanner) GetGoodsTypeId() int32 {
	if x != nil {
		return x.GoodsTypeId
	}
	return 0
}

func (x *IndexTypeGoodsBanner) GetGoodsSkuId() int32 {
	if x != nil {
		return x.GoodsSkuId
	}
	return 0
}

func (x *IndexTypeGoodsBanner) GetDisplayType() int32 {
	if x != nil {
		return x.DisplayType
	}
	return 0
}

func (x *IndexTypeGoodsBanner) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type IndexTypeGoodsBanners struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*IndexTypeGoodsBanner `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *IndexTypeGoodsBanners) Reset() {
	*x = IndexTypeGoodsBanners{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexTypeGoodsBanners) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexTypeGoodsBanners) ProtoMessage() {}

func (x *IndexTypeGoodsBanners) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexTypeGoodsBanners.ProtoReflect.Descriptor instead.
func (*IndexTypeGoodsBanners) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{10}
}

func (x *IndexTypeGoodsBanners) GetItems() []*IndexTypeGoodsBanner {
	if x != nil {
		return x.Items
	}
	return nil
}

// 商品详情页
type GoodsSku struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	GoodsId     int32  `protobuf:"varint,2,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
	GoodsTypeId int32  `protobuf:"varint,3,opt,name=GoodsTypeId,proto3" json:"GoodsTypeId,omitempty"`
	Name        string `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Desc        string `protobuf:"bytes,5,opt,name=Desc,proto3" json:"Desc,omitempty"`
	Price       int32  `protobuf:"varint,6,opt,name=Price,proto3" json:"Price,omitempty"`
	Unite       string `protobuf:"bytes,7,opt,name=Unite,proto3" json:"Unite,omitempty"`
	Image       string `protobuf:"bytes,8,opt,name=Image,proto3" json:"Image,omitempty"`
	Stock       int32  `protobuf:"varint,9,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Sales       int32  `protobuf:"varint,10,opt,name=Sales,proto3" json:"Sales,omitempty"`
	Status      int32  `protobuf:"varint,11,opt,name=Status,proto3" json:"Status,omitempty"`
	Time        string `protobuf:"bytes,12,opt,name=Time,proto3" json:"Time,omitempty"`
	Goods       *Goods `protobuf:"bytes,13,opt,name=Goods,proto3" json:"Goods,omitempty"`
}

func (x *GoodsSku) Reset() {
	*x = GoodsSku{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsSku) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsSku) ProtoMessage() {}

func (x *GoodsSku) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsSku.ProtoReflect.Descriptor instead.
func (*GoodsSku) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{11}
}

func (x *GoodsSku) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GoodsSku) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *GoodsSku) GetGoodsTypeId() int32 {
	if x != nil {
		return x.GoodsTypeId
	}
	return 0
}

func (x *GoodsSku) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodsSku) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *GoodsSku) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GoodsSku) GetUnite() string {
	if x != nil {
		return x.Unite
	}
	return ""
}

func (x *GoodsSku) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *GoodsSku) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GoodsSku) GetSales() int32 {
	if x != nil {
		return x.Sales
	}
	return 0
}

func (x *GoodsSku) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GoodsSku) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *GoodsSku) GetGoods() *Goods {
	if x != nil {
		return x.Goods
	}
	return nil
}

// 商品SPU
type Goods struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Detail string `protobuf:"bytes,3,opt,name=Detail,proto3" json:"Detail,omitempty"`
}

func (x *Goods) Reset() {
	*x = Goods{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Goods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goods) ProtoMessage() {}

func (x *Goods) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goods.ProtoReflect.Descriptor instead.
func (*Goods) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{12}
}

func (x *Goods) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Goods) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Goods) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_goods_proto protoreflect.FileDescriptor

var file_goods_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x18, 0x0a, 0x16, 0x46, 0x72, 0x65, 0x73, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x94, 0x03, 0x0a,
	0x17, 0x46, 0x72, 0x65, 0x73, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0b, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x47, 0x0a, 0x13, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x62, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73,
	0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x42, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x52, 0x11, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x42, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x73, 0x12, 0x53, 0x0a, 0x17, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x70, 0x72,
	0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x52, 0x15, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x4c, 0x0a, 0x0a, 0x67, 0x6f, 0x6f,
	0x64, 0x73, 0x5f, 0x6d, 0x61, 0x70, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x46, 0x72, 0x65, 0x73, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x4d, 0x61, 0x70, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x4d, 0x61, 0x70, 0x73, 0x1a, 0x5a, 0x0a, 0x0e, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x4d, 0x61, 0x70, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x32, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f,
	0x64, 0x73, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x47, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x6f, 0x6f,
	0x64, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x22, 0x45, 0x0a, 0x13,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x73, 0x6b, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x6b, 0x75, 0x52, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x53,
	0x6b, 0x75, 0x73, 0x22, 0x36, 0x0a, 0x12, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x67, 0x6f, 0x6f,
	0x64, 0x73, 0x5f, 0x73, 0x6b, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x6b, 0x75, 0x49, 0x64, 0x22, 0x73, 0x0a, 0x13, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x73, 0x6b, 0x75, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x53, 0x6b, 0x75, 0x52, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x6b, 0x75,
	0x12, 0x2e, 0x0a, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x73, 0x6b, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x53, 0x6b, 0x75, 0x52, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x6b, 0x75, 0x73,
	0x22, 0x59, 0x0a, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x6f, 0x67, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4c, 0x6f, 0x67, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x6e, 0x0a, 0x10, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x6b, 0x75, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x6b, 0x75, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x78, 0x0a, 0x14, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0xa0, 0x01, 0x0a, 0x14, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x54,
	0x79, 0x70, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x6b, 0x75, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x6b, 0x75, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x4a, 0x0a, 0x15, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x54, 0x79, 0x70, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x73, 0x12, 0x31, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x79,
	0x70, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0xbc, 0x02, 0x0a, 0x08, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x6b,
	0x75, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x65, 0x73, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x44, 0x65, 0x73, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x55,
	0x6e, 0x69, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x55, 0x6e, 0x69, 0x74,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x14, 0x0a,
	0x05, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x61,
	0x6c, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x22, 0x0a, 0x05, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x05, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x22, 0x43, 0x0a, 0x05, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x32, 0xeb, 0x02, 0x0a, 0x0c, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x77, 0x0a, 0x0f, 0x46, 0x72, 0x65,
	0x73, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1d, 0x2e, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x46, 0x72, 0x65, 0x73, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x2e, 0x46, 0x72, 0x65, 0x73, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x1f, 0x12, 0x1d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x6f, 0x6f,
	0x64, 0x73, 0x2f, 0x66, 0x72, 0x65, 0x73, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x79, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x12, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x30, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x2a, 0x12, 0x28, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x6f, 0x6f,
	0x64, 0x73, 0x2f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2f, 0x7b,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x73, 0x6b, 0x75, 0x5f, 0x69, 0x64, 0x7d, 0x12, 0x67, 0x0a,
	0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x19, 0x2e, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x12, 0x19, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x67, 0x6f, 0x6f,
	0x64, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_goods_proto_rawDescOnce sync.Once
	file_goods_proto_rawDescData = file_goods_proto_rawDesc
)

func file_goods_proto_rawDescGZIP() []byte {
	file_goods_proto_rawDescOnce.Do(func() {
		file_goods_proto_rawDescData = protoimpl.X.CompressGZIP(file_goods_proto_rawDescData)
	})
	return file_goods_proto_rawDescData
}

var file_goods_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_goods_proto_goTypes = []interface{}{
	(*FreshGoodsIndexRequest)(nil),  // 0: goods.FreshGoodsIndexRequest
	(*FreshGoodsIndexResponse)(nil), // 1: goods.FreshGoodsIndexResponse
	(*SearchGoodsRequest)(nil),      // 2: goods.SearchGoodsRequest
	(*SearchGoodsResponse)(nil),     // 3: goods.SearchGoodsResponse
	(*GoodsDetailRequest)(nil),      // 4: goods.GoodsDetailRequest
	(*GoodsDetailResponse)(nil),     // 5: goods.GoodsDetailResponse
	(*GoodsType)(nil),               // 6: goods.GoodsType
	(*IndexGoodsBanner)(nil),        // 7: goods.IndexGoodsBanner
	(*IndexPromotionBanner)(nil),    // 8: goods.IndexPromotionBanner
	(*IndexTypeGoodsBanner)(nil),    // 9: goods.IndexTypeGoodsBanner
	(*IndexTypeGoodsBanners)(nil),   // 10: goods.IndexTypeGoodsBanners
	(*GoodsSku)(nil),                // 11: goods.GoodsSku
	(*Goods)(nil),                   // 12: goods.Goods
	nil,                             // 13: goods.FreshGoodsIndexResponse.GoodsMapsEntry
}
var file_goods_proto_depIdxs = []int32{
	6,  // 0: goods.FreshGoodsIndexResponse.goods_types:type_name -> goods.GoodsType
	7,  // 1: goods.FreshGoodsIndexResponse.index_goods_banners:type_name -> goods.IndexGoodsBanner
	8,  // 2: goods.FreshGoodsIndexResponse.index_promotion_banners:type_name -> goods.IndexPromotionBanner
	13, // 3: goods.FreshGoodsIndexResponse.goods_maps:type_name -> goods.FreshGoodsIndexResponse.GoodsMapsEntry
	11, // 4: goods.SearchGoodsResponse.goods_skus:type_name -> goods.GoodsSku
	11, // 5: goods.GoodsDetailResponse.goods_sku:type_name -> goods.GoodsSku
	11, // 6: goods.GoodsDetailResponse.goods_skus:type_name -> goods.GoodsSku
	9,  // 7: goods.IndexTypeGoodsBanners.items:type_name -> goods.IndexTypeGoodsBanner
	12, // 8: goods.GoodsSku.Goods:type_name -> goods.Goods
	10, // 9: goods.FreshGoodsIndexResponse.GoodsMapsEntry.value:type_name -> goods.IndexTypeGoodsBanners
	0,  // 10: goods.GoodsService.FreshGoodsIndex:input_type -> goods.FreshGoodsIndexRequest
	4,  // 11: goods.GoodsService.GetGoodsDetail:input_type -> goods.GoodsDetailRequest
	2,  // 12: goods.GoodsService.SearchGoods:input_type -> goods.SearchGoodsRequest
	1,  // 13: goods.GoodsService.FreshGoodsIndex:output_type -> goods.FreshGoodsIndexResponse
	5,  // 14: goods.GoodsService.GetGoodsDetail:output_type -> goods.GoodsDetailResponse
	3,  // 15: goods.GoodsService.SearchGoods:output_type -> goods.SearchGoodsResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_goods_proto_init() }
func file_goods_proto_init() {
	if File_goods_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_goods_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FreshGoodsIndexRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FreshGoodsIndexResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchGoodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchGoodsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexGoodsBanner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexPromotionBanner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexTypeGoodsBanner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexTypeGoodsBanners); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsSku); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Goods); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_goods_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goods_proto_goTypes,
		DependencyIndexes: file_goods_proto_depIdxs,
		MessageInfos:      file_goods_proto_msgTypes,
	}.Build()
	File_goods_proto = out.File
	file_goods_proto_rawDesc = nil
	file_goods_proto_goTypes = nil
	file_goods_proto_depIdxs = nil
}
