// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: smscode.proto

package smscode

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SmsCodeService service

func NewSmsCodeServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		&api.Endpoint{
			Name:    "SmsCodeService.SendSmsCode",
			Path:    []string{"/api/v1/smscode"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
	}
}

// Client API for SmsCodeService service

type SmsCodeService interface {
	// Summary:发送短信验证码
	//
	// @Success 204 {object} SendSmsRequest
	//
	// @Failure 500 {object} SendSmsResponse
	//
	// test
	SendSmsCode(ctx context.Context, in *SendSmsRequest, opts ...client.CallOption) (*SendSmsResponse, error)
}

type smsCodeService struct {
	c    client.Client
	name string
}

func NewSmsCodeService(name string, c client.Client) SmsCodeService {
	return &smsCodeService{
		c:    c,
		name: name,
	}
}

func (c *smsCodeService) SendSmsCode(ctx context.Context, in *SendSmsRequest, opts ...client.CallOption) (*SendSmsResponse, error) {
	req := c.c.NewRequest(c.name, "SmsCodeService.SendSmsCode", in)
	out := new(SendSmsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SmsCodeService service

type SmsCodeServiceHandler interface {
	// Summary:发送短信验证码
	//
	// @Success 204 {object} SendSmsRequest
	//
	// @Failure 500 {object} SendSmsResponse
	//
	// test
	SendSmsCode(context.Context, *SendSmsRequest, *SendSmsResponse) error
}

func RegisterSmsCodeServiceHandler(s server.Server, hdlr SmsCodeServiceHandler, opts ...server.HandlerOption) error {
	type smsCodeService interface {
		SendSmsCode(ctx context.Context, in *SendSmsRequest, out *SendSmsResponse) error
	}
	type SmsCodeService struct {
		smsCodeService
	}
	h := &smsCodeServiceHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "SmsCodeService.SendSmsCode",
		Path:    []string{"/api/v1/smscode"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	return s.Handle(s.NewHandler(&SmsCodeService{h}, opts...))
}

type smsCodeServiceHandler struct {
	SmsCodeServiceHandler
}

func (h *smsCodeServiceHandler) SendSmsCode(ctx context.Context, in *SendSmsRequest, out *SendSmsResponse) error {
	return h.SmsCodeServiceHandler.SendSmsCode(ctx, in, out)
}
